name: Full-year calendar & Anilist metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    #environment: 
    #  name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Australia/Adelaide
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Australia/Adelaide
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: $ {{ secrets.ANILIST_USER}}
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 5
          
